[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for="/*.html"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[headers]]
  for="/sw.js"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
